### ISSUE TITLE
App crashes when browser window is resized with status bar overflow menu open

### ISSUE THREAD

**Issue by wilmaier** [iTwin/appui#1080]
### Describe the bug

App crashes when browser window is resized with status bar overflow menu open

**Getting this error message:**
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

### To Reproduce

1. Open any iModel in Pineapple
2. Resize the window to be small enough to see the ... on the right side of status bar
3. Click the ... button to open the overflow popup.
4. Resize the window left to right rapidly 
5. Sometimes it takes  a while for a crash

**NOTE:**  I also found that if the window width is set to 950px, it will crash immediately when opening the overflow popup

### Expected Behavior

Resize without issues

### Screenshots

![Image](https://github.com/user-attachments/assets/e5dc0026-a437-4786-b3fd-04f9d7967b81)

**Comment by wilmaier** [comment]
![Image](https://github.com/user-attachments/assets/3075f560-2876-4621-8e66-7f6719373292)



The above error occurred in the <button> component:

    at button
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:479122:63
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:478115:9
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:477359:9
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:468601:5
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:473763:5
    at StatusBarPopover (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:56993:29)
    at StatusBarOverflow (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:55881:13)
    at div
    at Div (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:344669:13)
    at StatusBarRightSection (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:56010:13)
    at div
    at Div (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:344669:13)
    at StatusBarSpaceBetween (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:55989:13)
    at div
    at StatusBarComposer (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:56238:13)
    at div
    at DockedBar (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:65015:13)
    at StatusBar (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:55979:63)
    at WidgetPanelsStatusBar (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:65895:108)
    at div
    at div
    at StandardLayout (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:37880:20)
    at PreviewHorizontalPanelAlignFeatureProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:51310:55)
    at MaximizedWidgetProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:51114:36)
    at WidgetPanelsFrontstageComponent (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:65194:126)
    at WidgetContentManager (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:44270:33)
    at CursorTypeProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:38778:79)
    at DraggedResizeHandleProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:38486:27)
    at DraggedPanelSideProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:38482:25)
    at DraggedWidgetIdProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:38478:29)
    at DragProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:38453:60)
    at NineZoneProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:38723:148)
    at NineZone (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:38709:13)
    at div
    at ActiveFrontstageDefProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:65292:40)
    at WidgetPanelsFrontstage (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:65274:108)
    at div
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:479122:63
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:476013:9
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:475999:105
    at ToastProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:476995:26)
    at HydrationProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:480556:30)
    at ScopeProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:480604:26)
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:475930:12
    at main
    at ConfigurableUiContent (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:29026:28)
    at RootComponent
    at UiStateStorageHandler (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:64148:80)
    at div
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:367962:13
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:367924:20
    at div
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:479122:63
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:476013:9
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:475999:105
    at ToastProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:476995:26)
    at HydrationProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:480556:30)
    at ScopeProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:480604:26)
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:475930:12
    at ThemeManager (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:58997:25)
    at PreviewFeaturesProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:50673:36)
    at IModelRecoil (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:76608:25)
    at RecoilRoot_INTERNAL (http://localhost:3000/static/js/vendors-node_modules_pnpm_bentley_icons-generic_1_0_34_node_modules_bentley_icons-generic_ico-9a04cc.chunk.js:356147:3)
    at RecoilRoot (http://localhost:3000/static/js/vendors-node_modules_pnpm_bentley_icons-generic_1_0_34_node_modules_bentley_icons-generic_ico-9a04cc.chunk.js:356313:5)
    at InnerPineappleBaseViewer (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:96385:100)
    at ErrorBoundary (http://localhost:3000/static/js/vendors-node_modules_pnpm_bentley_icons-generic_1_0_34_node_modules_bentley_icons-generic_ico-9a04cc.chunk.js:319819:5)
    at div
    at PineappleBaseViewer (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:96418:30)
    at IModelViewer (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:4607:5)
    at div
    at div
    at div
    at div
    at DevLayout (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:5784:5)
    at http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:6212:86
    at WithModuleDependencies (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:4647:7)
    at div
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:367962:13
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:367924:20
    at div
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:479122:63
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:476013:9
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:475999:105
    at ToastProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:476995:26)
    at HydrationProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:480556:30)
    at ScopeProvider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:480604:26)
    at http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:475930:12
    at ThemeManager (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:58997:25)
    at ThemeProvider (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:118131:26)
    at ThemeProvider (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:12779:5)
    at LaunchDarklyProvider (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:5302:5)
    at AutoLogin (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:550:5)
    at AuthProvider (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:590:5)
    at LocalizationProvider (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:6503:5)
    at PineappleTelemetryProvider (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:12304:5)
    at AppLoggerProvider (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:6844:5)
    at BrowserCompatibilityProvider (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:2144:5)
    at PineappleConfigProvider (http://localhost:3000/static/js/src_app_auth_AuthProvider_tsx-src_app_config_PineappleConfigProvider_tsx-src_app_imodel_Pinea-5b5b3c.chunk.js:1673:5)
    at Provider (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:405009:20)
    at PineappleApp (http://localhost:3000/static/js/src_app_PineappleApp_tsx.chunk.js:57:63)
    at Suspense
    at Route (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:407547:29)
    at Switch (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:407749:29)
    at Routes
    at C (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:407804:37)
    at Router (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:407166:30)
    at r (http://localhost:3000/static/js/vendors-node_modules_pnpm_itwin_appui-react_4_17_1__itwin_appui-abstract_4_9_3__itwin_compone-6901d5.chunk.js:404493:7350)
    at PineappleRouter
    at Suspense

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
