### ISSUE TITLE
Flaky Test in `@itwin/core-react` on `Winx64` - `ExpandableList should support singleExpandOnly & singleIsCollapsible props`

### ISSUE THREAD

**Issue by grigasp** [iTwin/appui#75]
#### Build Info

- Repo: https://github.com/iTwin/itwinjs-core
- Build Name: iTwin.js
- OS Winx64
- Test Suite Name: `@itwin/core-react`
- Test Name: `ExpandableList should support singleExpandOnly & singleIsCollapsible props`

#### Error Detail

```
  1) ExpandableList
       should support singleExpandOnly & singleIsCollapsible props:
     TestingLibraryElementError: Unable to find an element with the text: Hello1. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

  ...81 lines omitted...
  </div>
</body>
      at Object.getElementError (D:\vsts_a\3\s\common\temp\node_modules\.pnpm\@testing-library+dom@8.19.0\node_modules\@testing-library\dom\dist\config.js:40:19)
      at D:\vsts_a\3\s\common\temp\node_modules\.pnpm\@testing-library+dom@8.19.0\node_modules\@testing-library\dom\dist\query-helpers.js:90:38
      at D:\vsts_a\3\s\common\temp\node_modules\.pnpm\@testing-library+dom@8.19.0\node_modules\@testing-library\dom\dist\query-helpers.js:62:17
      at D:\vsts_a\3\s\common\temp\node_modules\.pnpm\@testing-library+dom@8.19.0\node_modules\@testing-library\dom\dist\query-helpers.js:111:19
      at Context.<anonymous> (src\test\expandable\ExpandableList.test.tsx:85:32)
```

### Links to failing builds

- **2023-01-02:** https://dev.azure.com/bentleycs/iModelTechnologies/_build/results?buildId=1875340&view=logs&j=9f3a3068-7880-5994-433d-b92c1f9d379b&t=c78dc741-fe12-5d6a-c099-5134f70fdb0c&l=22830

**Comment by GerardasB** [comment]
Haven't seen this failure in a while - closing.
